### ISSUE TITLE
Feature Request: LZ4 Compression Support

### ISSUE THREAD

**Issue by Quazz** [Genaker/FastFPC#10]
And possibly other compression types.

https://github.com/Genaker/FastFPC/blob/1632d2cdf81fa6b773e8e2f787160ee67ca5688d/Mage/FPC/FPC.php#L206

Insert something like

```    
        } elseif ($arch === 'l4') {
                return $page = lz4_uncompress(substr($page, 5));
        }
```

https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/blob/c2e14be4f38fcdc8ecbe609dc173a206db68bf6d/Cm/Cache/Backend/Redis.php#L1330

Can be used as a reference point.

**Comment by Genaker** [comment]
Why do you need another compression? Use the available one. Gzip.

**Comment by Quazz** [comment]
2 reasons:

The original Redis implementation of Magento will prefer basically any compression over gzip, so the transition to this extension would be much smoother if more compression types are supported. (you wont have to flush the entire full page cache)

The other reason is that other compression types offer superior performance in decompression as well as creating much smaller results, meaning less memory used by Redis, allowing for more pages to be cached.

**Comment by Genaker** [comment]
So, this one is not a commercial project. Only Gzip is supported, but if
you want to contribute more, you can
