### ISSUE TITLE
CSP header not sent when cache hit

### ISSUE THREAD

**Issue by MrTschi** [Genaker/FastFPC#6]
For cache-HITs, the Content-Security-Policy header is not returned to the viewer.

**Comment by Genaker** [comment]
Hi @MrTschi. If Magento sent this header, We are storing the headers. Please make var_dump() her content["header”] or something like that and check the headers stored by Magento.

**Comment by Genaker** [comment]
check this:
https://github.com/Genaker/FastFPC/blob/main/Mage/FPC/FPC.php#L131-L135
you probably have some specific issue.

**Comment by MrTschi** [comment]
Yes, but it seems like the CSP Header is not saved in redis.
I investigated a bit and it seems like redis-FPC is saved before CSP Headers are set. 

You could say its a magento bug, but with varnish it would work. 
any idea how to fix this?

**Comment by Genaker** [comment]
You need to fix this bug ;) I know how to fix.

But you can hard code all you headers.
Before echo $content :


Or you can set them in the Nginx. Etc.

**Comment by YehorShytikovWB** [comment]
> Yes, but it seems like the CSP Header is not saved in redis. I investigated a bit and it seems like redis-FPC is saved before CSP Headers are set.
> 
> You could say its a magento bug, but with varnish it would work. any idea how to fix this?
It is Open Magento issue: 
Some guys told me you need to set magento mode to production. I haven't tested it. 
https://github.com/magento/magento2/issues/37924
