### ISSUE TITLE
fpc-error	Redis config is not set

### ISSUE THREAD

**Issue by karthikmallireddy** [Genaker/FastFPC#9]
I'm receiving this error. It's not able to read the env.php file properly.

**Comment by Genaker** [comment]
Then redis config is not set. I think you'll be able to fix this issue.

**Comment by karthikmallireddy** [comment]
I'm getting this error when i'm using redis with unix socket.

**Comment by karthikmallireddy** [comment]
It's sorted and fixed now thanks
